### ISSUE TITLE
Enhancement: Update Demo Functionality

### ISSUE THREAD

**Issue by DESHRAJ** [batra-mlp-lab/CloudCVfy-Frontend#12]
If the user updates the code on github, then he should only have to come back to CVfy frontend and press the `Update demo` demo button which redeploys the demo automatically.

**Comment by tocttou** [comment]
When the user comes back to the code and presses the "Modify Demo" button, he is taken through a process of:

1. Update metadata
2. Update I/O components
3. Attempt to redeploy

I have to check if 3 is working or not (it probably just dismisses the update since container is running).

Also its better to also allow user to select what he wants to update instead of going through the hoops.

**Comment by tocttou** [comment]
#15 is about this.

**Comment by DESHRAJ** [comment]
Yeah sure, this approach sounds good in terms of UX. Keep me posted when this is up on the test server so that I can check.

**Comment by tocttou** [comment]
This is on hiatus after the discussion in last meeting. Github build system is too confusing (and fragile as well) and requires much more time to polish. The code is still there but only the entrypoint commented out. Closing this until something concrete is figured out about that workflow.
